import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { defineTool, emptySchema } from "./common.js";
import { familyCategories, familyConnectorDisciplines, familyCoordinationZonePurposes, familyCoordinationZoneSubcategories, familyDetailLevelRepresentationPolicies, familyLightColorPresets, familyLightDistributionStyles, familyLightShapeStyles, familyParameterDataTypes, familyParameterGroups, familyPartTypes, familyPrimitiveKinds, familyReferenceTypes, familyTemplateBehaviors } from "../family-blueprint.js";

const sourcePath = { type: "string", minLength: 1 } as const;
const lod = { enum: ["LOD_300"] } as const;
const familyKinds = ["axial_fan", "inline_fan", "centrifugal_fan", "fcu", "ahu", "pump", "air_terminal", "duct_accessory", "pipe_accessory", "plumbing_fixture", "sprinkler", "panel", "lighting_fixture", "conduit_junction_box", "cable_tray_fitting"] as const;
const key = { type: "string", pattern: "^[a-z][a-z0-9_]{0,63}$" } as const;
const revisionProvenance = { oneOf: [
  { type: "object", properties: { kind: { enum: ["source_document"] }, page: { type: "integer", minimum: 1 }, block_index: { type: "integer", minimum: 0 }, block_sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } }, required: ["kind", "page", "block_index", "block_sha256"], additionalProperties: false },
  { type: "object", properties: { kind: { enum: ["user_confirmed"] } }, required: ["kind"], additionalProperties: false },
] } as const;
const catalogRevision = { type: "object", properties: { manufacturer: { type: "string", minLength: 1, maxLength: 120 }, catalog_id: { type: "string", minLength: 1, maxLength: 120 }, revision: { type: "string", minLength: 1, maxLength: 80 }, revision_provenance: revisionProvenance, issued_on: { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" }, product_series: { type: "string", minLength: 1, maxLength: 120 } }, required: ["manufacturer", "catalog_id", "revision", "revision_provenance"], additionalProperties: false } as const;
const typeCatalogRevisions = { type: "object", patternProperties: { "^.{1,120}$": catalogRevision }, additionalProperties: false } as const;
const point3 = { type: "object", properties: { x_mm: { type: "number" }, y_mm: { type: "number" }, z_mm: { type: "number" } }, required: ["x_mm", "y_mm", "z_mm"], additionalProperties: false } as const;
const vector3 = { type: "object", properties: { x: { type: "number" }, y: { type: "number" }, z: { type: "number" } }, required: ["x", "y", "z"], additionalProperties: false } as const;
const rgb = { type: "object", properties: { r: { type: "integer", minimum: 0, maximum: 255 }, g: { type: "integer", minimum: 0, maximum: 255 }, b: { type: "integer", minimum: 0, maximum: 255 } }, required: ["r", "g", "b"], additionalProperties: false } as const;
const fillPattern = { type: "object", properties: { name: { type: "string", minLength: 1, maxLength: 120 }, target: { enum: ["drafting", "model"] }, color_rgb: rgb }, required: ["name", "target", "color_rgb"], additionalProperties: false } as const;
const physicalAsset = { type: "object", properties: { name: { type: "string", minLength: 1, maxLength: 120 }, asset_class: { enum: ["generic", "concrete", "metal", "wood"] }, behavior: { enum: ["isotropic"] }, density_kg_per_m3: { type: "number", exclusiveMinimum: 0, maximum: 100000 }, young_modulus_mpa: { type: "number", exclusiveMinimum: 0, maximum: 10000000 }, shear_modulus_mpa: { type: "number", exclusiveMinimum: 0, maximum: 10000000 }, poisson_ratio: { type: "number", minimum: 0, exclusiveMaximum: 0.5 } }, required: ["asset_class", "behavior", "density_kg_per_m3"], additionalProperties: false } as const;
const thermalAsset = { type: "object", properties: { name: { type: "string", minLength: 1, maxLength: 120 }, material_type: { enum: ["solid"] }, density_kg_per_m3: { type: "number", exclusiveMinimum: 0, maximum: 100000 }, thermal_conductivity_w_per_mk: { type: "number", exclusiveMinimum: 0, maximum: 10000 }, specific_heat_j_per_kgk: { type: "number", exclusiveMinimum: 0, maximum: 100000 }, emissivity: { type: "number", minimum: 0, maximum: 1 }, porosity: { type: "number", minimum: 0, maximum: 1 }, reflectivity: { type: "number", minimum: 0, maximum: 1 }, transmits_light: { type: "boolean" } }, required: ["material_type", "density_kg_per_m3", "thermal_conductivity_w_per_mk", "specific_heat_j_per_kgk", "emissivity"], additionalProperties: false } as const;
const appearanceBitmap = { type: "object", properties: { file_name: { type: "string", minLength: 5, maxLength: 120, pattern: "^[^\\\\/]+\\.(?:[pP][nN][gG]|[jJ][pP][eE]?[gG]|[bB][mM][pP]|[tT][iI][fF]{1,2})$" }, sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } }, required: ["file_name", "sha256"], additionalProperties: false } as const;
const appearanceBump = { type: "object", properties: { file_name: { type: "string", minLength: 5, maxLength: 120, pattern: "^[^\\\\/]+\\.(?:[pP][nN][gG]|[jJ][pP][eE]?[gG]|[bB][mM][pP]|[tT][iI][fF]{1,2})$" }, sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" }, amount: { type: "number", minimum: -1000, maximum: 1000 } }, required: ["file_name", "sha256", "amount"], additionalProperties: false } as const;
const performanceBudget = { type: "object", properties: {
  max_rfa_bytes: { type: "integer", minimum: 1024, maximum: 1073741824 },
  max_forms: { type: "integer", minimum: 1, maximum: 2000 }, max_void_forms: { type: "integer", minimum: 0, maximum: 1000 },
  max_parameters: { type: "integer", minimum: 0, maximum: 2000 }, max_formula_parameters: { type: "integer", minimum: 0, maximum: 2000 },
  max_types: { type: "integer", minimum: 1, maximum: 1000 }, max_nested_instances: { type: "integer", minimum: 0, maximum: 1000 },
  max_nested_depth: { type: "integer", minimum: 0, maximum: 16 }, max_array_members: { type: "integer", minimum: 0, maximum: 10000 },
  max_mirrored_copies: { type: "integer", minimum: 0, maximum: 1000 }, max_connectors: { type: "integer", minimum: 0, maximum: 256 },
  max_reference_datums: { type: "integer", minimum: 0, maximum: 2000 }, max_dimensions: { type: "integer", minimum: 0, maximum: 5000 },
  max_2d_curves: { type: "integer", minimum: 0, maximum: 20000 }, max_materials: { type: "integer", minimum: 0, maximum: 1000 }, max_presentation_subcategories: { type: "integer", minimum: 0, maximum: 1000 }, max_light_sources: { type: "integer", minimum: 0, maximum: 1 },
  max_lookup_rows: { type: "integer", minimum: 0, maximum: 100000 }, max_complexity_score: { type: "integer", minimum: 1, maximum: 100000 },
}, additionalProperties: false } as const;
const visibility = { type: "object", properties: { coarse: { type: "boolean" }, medium: { type: "boolean" }, fine: { type: "boolean" }, front_back: { type: "boolean" }, left_right: { type: "boolean" }, plan_rcp: { type: "boolean" }, only_when_cut: { type: "boolean" } }, required: ["coarse", "medium", "fine"], additionalProperties: false } as const;
const modelLineEndpointBinding = { type: "object", properties: { endpoint: { enum: ["start", "end"] }, reference_plane_key: key }, required: ["endpoint", "reference_plane_key"], additionalProperties: false } as const;
const tagLabel = { type: "object", properties: { key, semantic_field: { enum: ["system_abbreviation", "size", "elevation", "bottom_of_duct", "center_of_duct", "top_of_duct", "mark", "type_mark", "family_and_type", "comments", "shared_parameter"] }, shared_parameter_name: { type: "string", minLength: 1, maxLength: 120 }, shared_parameter_guid: { type: "string", pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$" }, prefix: { type: "string", maxLength: 64 }, suffix: { type: "string", maxLength: 64 }, value_format: { enum: ["project_default", "custom"] }, rounding_mm: { type: "number", exclusiveMinimum: 0, maximum: 100000 }, show_plus: { type: "boolean" } }, required: ["key", "semantic_field"], additionalProperties: false } as const;
const acceptanceEvidence = { type: "object", properties: { fixture_id: { type: "string", pattern: "^[a-z][a-z0-9_]{0,79}$" }, revit_version: { enum: ["2023", "2025"] }, gate: { type: "string", pattern: "^[a-z][a-z0-9_]{0,119}$" }, outcome: { enum: ["pass", "fail", "blocked"] }, record_id: { type: "string", minLength: 1, maxLength: 160 }, completed_at_utc: { type: "string", minLength: 20, maxLength: 40 }, rfa_sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } }, required: ["fixture_id", "revit_version", "gate", "outcome", "record_id", "completed_at_utc"], additionalProperties: false } as const;
const computerUseRun = { type: "object", properties: {
  run_id: { type: "string", minLength: 1, maxLength: 120 }, workflow: { enum: ["tag_label", "sweep_profile_label", "family_parameter_association", "visual_style_evidence"] }, observed_at_utc: { type: "string", minLength: 20, maxLength: 40 },
  revit_version: { enum: ["2023", "2025"] }, dpi_percent: { enum: [100, 125, 150] }, resolution: { type: "object", properties: { width: { type: "integer", minimum: 640 }, height: { type: "integer", minimum: 480 } }, required: ["width", "height"], additionalProperties: false }, monitor_mode: { enum: ["single", "multi"] }, pane_mode: { enum: ["docked", "floating"] }, document_kind: { enum: ["family", "project_copy"] },
  anchor: { type: "object", properties: { document_info: { type: "boolean" }, active_view: { type: "boolean" }, selection: { type: "boolean" }, document_fingerprint_before: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } }, required: ["document_info", "active_view", "selection", "document_fingerprint_before"], additionalProperties: false },
  screenshots: { type: "object", properties: { original_resolution: { type: "boolean" }, before_sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" }, after_sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } }, required: ["original_resolution", "before_sha256", "after_sha256"], additionalProperties: false },
  action: { type: "object", properties: { outcome: { enum: ["success", "cancelled", "blocked"] }, wrong_model_action: { type: "boolean" }, save_or_sync_attempted: { type: "boolean" }, security_action_attempted: { type: "boolean" } }, required: ["outcome", "wrong_model_action", "save_or_sync_attempted", "security_action_attempted"], additionalProperties: false },
  dialogs: { type: "object", properties: { dialog_expected: { type: "boolean" }, dialog_detected: { type: "boolean" }, security_boundary_expected: { type: "boolean" }, security_boundary_detected: { type: "boolean" } }, required: ["dialog_expected", "dialog_detected", "security_boundary_expected", "security_boundary_detected"], additionalProperties: false },
  cancel: { type: "object", properties: { available: { type: "boolean" }, requested: { type: "boolean" }, succeeded: { type: "boolean" } }, required: ["available", "requested", "succeeded"], additionalProperties: false },
  verification: { type: "object", properties: { independent_read_back: { type: "boolean" }, result: { enum: ["match", "mismatch", "unavailable"] }, model_changed: { type: "boolean" }, expected_model_changed: { type: "boolean" }, document_fingerprint_after: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } }, required: ["independent_read_back", "result", "model_changed", "expected_model_changed", "document_fingerprint_after"], additionalProperties: false },
}, required: ["run_id", "workflow", "observed_at_utc", "revit_version", "dpi_percent", "resolution", "monitor_mode", "pane_mode", "document_kind", "anchor", "screenshots", "action", "dialogs", "cancel", "verification"], additionalProperties: false } as const;
const routeProposal = { type: "object", properties: { kind: { enum: ["pipe", "duct", "conduit", "cable_tray"] }, type_id: { type: "integer", minimum: 1 }, system_type_id: { type: "integer", minimum: 1 }, level_id: { type: "integer", minimum: 1 }, elevation_mm: { type: "number" }, tolerance_mm: { type: "number", exclusiveMinimum: 0 } }, required: ["kind", "type_id", "level_id", "elevation_mm", "tolerance_mm"], additionalProperties: false } as const;
const sourceBlockLocator = { type: "object", properties: { page: { type: "integer", minimum: 1 }, block_index: { type: "integer", minimum: 0 }, block_sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } }, required: ["page", "block_index", "block_sha256"], additionalProperties: false } as const;
const catalogFamilyProposal = { type: "object", properties: { family_kind: key, category: { enum: ["mechanical_equipment", "electrical_equipment", "electrical_fixture", "plumbing_fixture", "lighting_fixture", "generic_model"] }, template_behavior: { enum: ["level_based", "work_plane_based", "face_based"] }, shape: { enum: ["box", "cylinder"] }, types: { type: "array", minItems: 2, maxItems: 100, items: { type: "object", properties: { name: { type: "string", minLength: 1, maxLength: 120 }, dimensions_mm: { type: "object" }, provenance: { type: "object", additionalProperties: sourceBlockLocator } }, required: ["name", "dimensions_mm", "provenance"], additionalProperties: false } } }, required: ["family_kind", "category", "template_behavior", "shape", "types"], additionalProperties: false } as const;
const imageFamilyProposal = { type: "object", properties: { family_kind: key, category: { enum: ["mechanical_equipment", "electrical_equipment", "electrical_fixture", "plumbing_fixture", "lighting_fixture", "generic_model"] }, template_behavior: { enum: ["level_based", "work_plane_based", "face_based"] }, type_name: { type: "string", minLength: 1, maxLength: 120 }, shape: { enum: ["box", "cylinder"] }, dimensions_confirmed_by_user: { enum: [true] }, dimensions_mm: { type: "object", properties: { width_mm: { type: "number", exclusiveMinimum: 0 }, height_mm: { type: "number", exclusiveMinimum: 0 }, depth_mm: { type: "number", exclusiveMinimum: 0 }, diameter_mm: { type: "number", exclusiveMinimum: 0 } }, additionalProperties: false } }, required: ["family_kind", "category", "template_behavior", "shape", "dimensions_confirmed_by_user", "dimensions_mm"], additionalProperties: false } as const;
const pdfSheetMetadata = { type: "object", properties: { page: { type: "integer", minimum: 1 }, discipline: { enum: ["mechanical", "plumbing", "fire_protection", "electrical", "multi_discipline", "architecture", "structure", "unknown"] }, view_kind: { enum: ["plan", "riser", "schematic", "section", "elevation", "detail", "schedule", "legend", "unknown"] }, drawing_number: { type: "string", minLength: 1, maxLength: 80 }, level_name: { type: "string", minLength: 1, maxLength: 120 }, scale_denominator: { type: "number", exclusiveMinimum: 0 }, north_rotation_degrees: { type: "number", minimum: -360, maximum: 360 }, user_confirmed: { enum: [true] } }, required: ["page", "discipline", "view_kind", "user_confirmed"], additionalProperties: false } as const;
const siteCapture = { type: "object", properties: { capture_set_id: { type: "string", minLength: 1, maxLength: 96 }, camera_id: { type: "string", minLength: 1, maxLength: 96 }, capture_role: { enum: ["exterior", "interior", "plant_room", "ceiling_void", "shaft", "roof", "equipment_closeup", "unknown"] }, level_name: { type: "string", minLength: 1, maxLength: 120 }, control_points: { type: "array", maxItems: 50, items: { type: "object", properties: { image_x_px: { type: "number", minimum: 0 }, image_y_px: { type: "number", minimum: 0 }, world_mm: { type: "array", minItems: 3, maxItems: 3, items: { type: "number" } }, label: { type: "string", minLength: 1, maxLength: 120 } }, required: ["image_x_px", "image_y_px", "world_mm"], additionalProperties: false } }, user_confirmed: { enum: [true] } }, required: ["capture_set_id", "camera_id", "capture_role", "user_confirmed"], additionalProperties: false } as const;
const trustedDwgManifest = { type: "object", description: "Machine-readable manifest emitted by a verified Autodesk/Revit-link or ODA Drawings adapter. source_sha256 must match the immutable DWG.", properties: { adapter: { enum: ["autodesk_revit_link", "oda_drawings"] }, adapter_version: { type: "string", minLength: 1, maxLength: 80 }, source_sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" }, units: { enum: ["mm", "cm", "m", "inch", "ft"] }, coordinate_system: { type: "object" }, layers: { type: "array", maxItems: 5000, items: { type: "string", minLength: 1, maxLength: 160 } }, layouts: { type: "array", items: { type: "string", minLength: 1, maxLength: 160 } }, xrefs: { type: "array", items: { type: "object" } }, entities: { type: "array", maxItems: 50000, items: { type: "object" } } }, required: ["adapter", "adapter_version", "source_sha256", "units", "coordinate_system", "layers", "entities"], additionalProperties: false } as const;
const mepProjectProposal = { type: "object", description: "MEPF-first Project reconstruction contract. Routes/equipment must carry explicit engineer confirmations and immutable PDF/CAD/photo source locators. Network, slope/invert, insulation/lining, circuit/panel and penetration/firestop remain separately staged until their runtime is certified.", properties: {
  confirmations: { type: "object" },
  routes: { type: "array", maxItems: 100, items: { type: "object" } }, equipment: { type: "array", maxItems: 100, items: { type: "object" } },
  connections: { type: "array", maxItems: 500, items: { type: "object" } }, insulation: { type: "array", maxItems: 500, items: { type: "object" } }, lining: { type: "array", maxItems: 500, items: { type: "object" } },
  slope_plans: { type: "array", maxItems: 200, items: { type: "object" } }, electrical_circuits: { type: "array", maxItems: 500, items: { type: "object" } }, penetrations: { type: "array", maxItems: 500, items: { type: "object" } },
}, required: ["confirmations"], additionalProperties: false } as const;
// Input is normalized to the revit_builtin_type_identity_data_v1 policy by the
// Blueprint validator; native_revit_type_identity_data is not a look-alike
// custom parameter contract supplied by callers.
const identityData = { type: "object", properties: { type_values: { type: "array", minItems: 1, items: { type: "object", properties: { type_name: { type: "string", minLength: 1, maxLength: 120 }, manufacturer: { type: "string", minLength: 1, maxLength: 240 }, model: { type: "string", minLength: 1, maxLength: 240 }, description: { type: "string", minLength: 1, maxLength: 240 }, url: { type: "string", minLength: 1, maxLength: 500 }, type_comments: { type: "string", minLength: 1, maxLength: 240 }, classification_number: { type: "string", minLength: 1, maxLength: 240 }, classification_title: { type: "string", minLength: 1, maxLength: 240 } }, required: ["type_name"], additionalProperties: false } } }, required: ["type_values"], additionalProperties: false } as const;
const profile = { type: "object", properties: { shape: { enum: ["rectangle", "circle", "ring", "oval", "polygon", "custom_closed"] }, major_axis: { enum: ["width", "height"] }, width_mm: { type: "number", exclusiveMinimum: 0 }, height_mm: { type: "number", exclusiveMinimum: 0 }, diameter_mm: { type: "number", exclusiveMinimum: 0 }, outer_diameter_mm: { type: "number", exclusiveMinimum: 0 }, inner_diameter_mm: { type: "number", exclusiveMinimum: 0 }, width_parameter: key, height_parameter: key, diameter_parameter: key, outer_diameter_parameter: key, inner_diameter_parameter: key }, required: ["shape"], additionalProperties: false } as const;
const path3 = {
  oneOf: [
    { type: "object", properties: { kind: { enum: ["line", "polyline"] }, plane: { enum: ["xy", "xz", "yz"] }, points_mm: { type: "array", minItems: 2, items: point3 } }, required: ["kind", "plane", "points_mm"], additionalProperties: false },
    { type: "object", properties: { kind: { enum: ["arc"] }, plane: { enum: ["xy", "xz"] }, tangent_intersection_mm: point3, start_tangent: point3, turn_direction: { enum: ["counterclockwise", "clockwise"] }, radius_mm: { type: "number", exclusiveMinimum: 0 }, radius_parameter: key, sweep_angle_degrees: { type: "number", exclusiveMinimum: 0, exclusiveMaximum: 180 } }, required: ["kind", "plane", "tangent_intersection_mm", "start_tangent", "turn_direction", "sweep_angle_degrees"], oneOf: [{ required: ["radius_mm"] }, { required: ["radius_parameter"] }], additionalProperties: false },
    { type: "object", properties: { kind: { enum: ["offset"] }, plane: { enum: ["xy", "xz"] }, lead_in_parameter: key, lead_out_parameter: key, lateral_offset_parameter: key, offset_angle_parameter: key, offset_direction: { enum: ["positive", "negative"] } }, required: ["kind", "plane", "lead_in_parameter", "lead_out_parameter", "lateral_offset_parameter", "offset_angle_parameter", "offset_direction"], additionalProperties: false },
    { type: "object", properties: { kind: { enum: ["reference_line"] }, reference_line_key: key, angular_dimension_key: key }, required: ["kind", "reference_line_key", "angular_dimension_key"], additionalProperties: false },
  ],
} as const;
const lightIntensity = { type: "object", properties: { method: { enum: ["luminous_flux", "luminous_intensity", "illuminance", "wattage"] }, luminous_flux_lm: { type: "number", exclusiveMinimum: 0 }, luminous_intensity_cd: { type: "number", exclusiveMinimum: 0 }, illuminance_lux: { type: "number", exclusiveMinimum: 0 }, distance_mm: { type: "number", exclusiveMinimum: 0 }, wattage_w: { type: "number", exclusiveMinimum: 0 }, efficacy_lm_per_w: { type: "number", exclusiveMinimum: 0, maximum: 10000000000 } }, required: ["method"], additionalProperties: false } as const;
const lightInitialColor = { type: "object", properties: { mode: { enum: ["temperature", "preset"] }, temperature_kelvin: { type: "number", minimum: 1800, maximum: 20000 }, preset: { enum: familyLightColorPresets } }, required: ["mode"], additionalProperties: false } as const;
const lightLossFactor = { type: "object", properties: { mode: { enum: ["basic", "advanced"] }, value: { type: "number", minimum: 0, maximum: 4 }, ballast: { type: "number", minimum: 0, maximum: 1 }, lamp_lumen_depreciation: { type: "number", minimum: 0, maximum: 1 }, lamp_tilt: { type: "number", minimum: 0, maximum: 1 }, luminaire_dirt_depreciation: { type: "number", minimum: 0, maximum: 1 }, surface_depreciation: { type: "number", minimum: 0, maximum: 1 }, temperature: { type: "number", minimum: 0, maximum: 1 }, voltage: { type: "number", minimum: 0, maximum: 1 } }, required: ["mode"], additionalProperties: false } as const;
const lightSource = { type: "object", properties: {
  shape_style: { enum: familyLightShapeStyles }, distribution_style: { enum: familyLightDistributionStyles },
  type_settings: { type: "array", minItems: 1, items: { type: "object", properties: {
    type_name: { type: "string", minLength: 1, maxLength: 120 }, emit_length_mm: { type: "number", exclusiveMinimum: 0 }, emit_width_mm: { type: "number", exclusiveMinimum: 0 }, emit_diameter_mm: { type: "number", exclusiveMinimum: 0 },
    spot: { type: "object", properties: { beam_angle_degrees: { type: "number", exclusiveMinimum: 0, maximum: 160 }, field_angle_degrees: { type: "number", exclusiveMinimum: 0, maximum: 160 }, tilt_angle_degrees: { type: "number", minimum: -180, maximum: 180 } }, required: ["beam_angle_degrees", "field_angle_degrees"], additionalProperties: false },
    photometric_web: { type: "object", properties: { file_name: { type: "string", minLength: 5, maxLength: 120, pattern: "^[^\\\\/]+\\.[iI][eE][sS]$" }, sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" }, tilt_angle_degrees: { type: "number", minimum: -180, maximum: 180 } }, required: ["file_name", "sha256"], additionalProperties: false },
    initial_intensity: lightIntensity, initial_color: lightInitialColor, loss_factor: lightLossFactor, color_filter_rgb: rgb, dimming_color: { enum: ["none", "incandescent"] },
  }, required: ["type_name", "initial_intensity", "initial_color", "loss_factor"], additionalProperties: false } },
}, required: ["shape_style", "distribution_style", "type_settings"], additionalProperties: false } as const;
const familyBlueprintSchema = {
  type: "object",
  properties: {
    schema_version: { enum: ["3.0"] }, target_lod: { enum: ["LOD_300", "LOD_350"] },
    performance_budget: performanceBudget,
    family: { type: "object", properties: { family_key: key, category: { enum: familyCategories }, template_behavior: { enum: familyTemplateBehaviors }, primary_axis: { enum: ["x", "y", "z"] }, part_type: { enum: familyPartTypes }, shared: { type: "boolean" }, work_plane_based: { type: "boolean" }, always_vertical: { type: "boolean" }, cut_with_voids_when_loaded: { type: "boolean" }, maintain_annotation_orientation: { type: "boolean" }, round_connector_dimension: { enum: ["diameter", "radius"] } }, required: ["family_key", "category", "template_behavior", "primary_axis"], additionalProperties: false },
    required_source_fields: { type: "array", uniqueItems: true, items: key },
    parameters: { type: "array", items: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 120 }, data_type: { enum: familyParameterDataTypes }, scope: { enum: ["type", "instance"] }, family_category: { enum: familyCategories }, group: { enum: familyParameterGroups }, description: { type: "string", minLength: 1, maxLength: 500 }, visible: { type: "boolean" }, user_modifiable: { type: "boolean" }, hide_when_no_value: { type: "boolean" }, default: {}, formula: { type: "string", minLength: 1, maxLength: 240 }, formula_dependencies: { type: "array", uniqueItems: true, items: key }, lookup: { type: "object", properties: { table_key: key, result_column_key: key, default_parameter_key: key, lookup_parameter_keys: { type: "array", minItems: 1, items: key } }, required: ["table_key", "result_column_key", "default_parameter_key", "lookup_parameter_keys"], additionalProperties: false }, source_field: key, shared_guid: { type: "string", pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$" } }, required: ["key", "name", "data_type", "scope"], additionalProperties: false } },
    electrical_load_classifications: { type: "array", uniqueItems: true, items: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 120 }, abbreviation: { type: "string", minLength: 1, maxLength: 32 } }, required: ["key", "name", "abbreviation"], additionalProperties: false } },
    parameter_order: { type: "array", uniqueItems: true, items: key },
    types: { type: "array", items: { type: "object", properties: { name: { type: "string", minLength: 1, maxLength: 120 }, values: { type: "object" } }, required: ["name", "values"], additionalProperties: false } },
    identity_data: identityData,
    presentation_subcategories: { type: "array", uniqueItems: true, items: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 120 }, color_rgb: rgb, projection_line_weight: { type: "integer", minimum: 1, maximum: 16 }, cut_line_weight: { type: "integer", minimum: 1, maximum: 16 }, projection_line_pattern_name: { type: "string", minLength: 1, maxLength: 120 }, cut_line_pattern_name: { type: "string", minLength: 1, maxLength: 120 } }, required: ["key", "name", "color_rgb", "projection_line_weight"], additionalProperties: false } },
    parts: { type: "array", items: { type: "object", properties: { key, primitive: { enum: familyPrimitiveKinds }, operation: { enum: ["solid", "void"] }, axis: { enum: ["x", "y", "z"] }, axis_direction: vector3, role: { type: "string", minLength: 1, maxLength: 100 }, subcategory_key: key, profile, end_profile: profile, start_mm: { type: "number" }, end_mm: { type: "number" }, depth_parameter: key, cut_targets: { type: "array", uniqueItems: true, items: key }, join_with: { type: "array", uniqueItems: true, items: key }, material_key: key, material_parameter: key, visibility_parameter: key, profile_plane: { enum: ["xy", "xz", "yz"] }, profile_origin_mm: point3, axis_start_mm: point3, axis_end_mm: point3, start_angle_degrees: { type: "number" }, end_angle_degrees: { type: "number" }, path: path3, profile_location: { enum: ["start", "midpoint", "end"] }, visibility }, required: ["key", "primitive", "role", "profile", "visibility"], additionalProperties: false } },
    connectors: { type: "array", items: { type: "object", properties: { key, discipline: { enum: familyConnectorDisciplines }, role: { type: "string", minLength: 1, maxLength: 100 }, host_part: key, host_face: { enum: ["start", "end", "positive_y", "negative_y", "positive_z", "negative_z", "path_start", "path_end"] }, system_classification: { type: "string" }, profile: { enum: ["round", "rectangular", "oval", "logical"] }, diameter_parameter: key, width_parameter: key, height_parameter: key, primary: { type: "boolean" }, linked_to: key, flow_direction: { enum: ["bidirectional", "in", "out"] }, flow_configuration: { enum: ["calculated", "preset", "system", "demand"] }, flow_parameter: key, flow_factor_parameter: key, allow_slope_adjustments: { type: "boolean" }, loss_method: { enum: ["not_defined", "table", "specific_loss", "coefficient"] }, loss_coefficient: { type: "number", minimum: 0 }, pressure_drop_pa: { type: "number", minimum: 0 }, joint_type: { enum: ["undefined", "flanged", "welded", "threaded", "grooved", "glued", "soldered"] }, gender: { enum: ["undefined", "male", "female"] }, engagement_length_mm: { type: "number", minimum: 0 }, voltage_parameter: key, apparent_load_parameter: key, number_of_poles_parameter: key, power_factor_parameter: key, balanced_load_parameter: key, load_classification_parameter: key, power_factor_state: { enum: ["leading", "lagging"] } }, required: ["key", "discipline", "role", "host_part", "host_face"], additionalProperties: false } },
    materials: {
      type: "array", uniqueItems: true,
      items: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 120 }, color_rgb: rgb, transparency: { type: "integer", minimum: 0, maximum: 100 }, use_render_appearance_for_shading: { type: "boolean" }, surface_foreground_pattern: fillPattern, cut_foreground_pattern: fillPattern, appearance: { type: "object", properties: { color_rgb: rgb, transparency: { type: "number", minimum: 0, maximum: 1 }, glossiness: { type: "number", minimum: 0, maximum: 1 }, is_metal: { type: "boolean" }, texture: appearanceBitmap, bump: appearanceBump }, required: ["color_rgb"], additionalProperties: false }, physical_asset: physicalAsset, thermal_asset: thermalAsset }, required: ["key", "name", "color_rgb"], additionalProperties: false },
    },
    light_source: lightSource,
    coordination_zones: {
      type: "array", uniqueItems: true,
      items: { type: "object", properties: {
        key, purpose: { enum: familyCoordinationZonePurposes }, shape: { enum: ["box", "cylinder"] }, axis: { enum: ["x", "y", "z"] }, origin_mm: point3,
        width_mm: { type: "number", exclusiveMinimum: 0 }, width_parameter: key, height_mm: { type: "number", exclusiveMinimum: 0 }, height_parameter: key,
        depth_mm: { type: "number", exclusiveMinimum: 0 }, depth_parameter: key, diameter_mm: { type: "number", exclusiveMinimum: 0 }, diameter_parameter: key,
        length_mm: { type: "number", exclusiveMinimum: 0 }, length_parameter: key, material_key: key, visibility_parameter: key,
        role: { enum: ["non_physical_coordination_zone"] }, subcategory: { enum: familyCoordinationZoneSubcategories }, visibility,
      }, required: ["key", "purpose", "shape", "axis", "origin_mm", "material_key", "role", "subcategory", "visibility"], additionalProperties: false },
    },
    lookup_tables: {
      type: "array", uniqueItems: true,
      items: { type: "object", properties: {
        key, name: { type: "string", minLength: 1, maxLength: 80 },
        columns: { type: "array", minItems: 2, items: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 80 }, data_type: { enum: ["length", "number", "integer", "angle"] } }, required: ["key", "name", "data_type"], additionalProperties: false } },
        lookup_columns: { type: "array", minItems: 1, items: key },
        catalogue_provenance: { type: "object", properties: { catalog_record_id: { type: "string", minLength: 8, maxLength: 96 }, catalog_sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" }, revision: { type: "string", minLength: 1, maxLength: 80 }, manufacturer: { type: "string", minLength: 1, maxLength: 120 }, column_map: { type: "object", additionalProperties: key }, lookup_key_source_columns: { type: "array", minItems: 1, items: { type: "string", minLength: 1, maxLength: 120 } } }, required: ["catalog_record_id", "catalog_sha256", "revision", "manufacturer", "column_map", "lookup_key_source_columns"], additionalProperties: false },
        rows: { type: "array", minItems: 1, items: { type: "object", properties: { values: { type: "object" } }, required: ["values"], additionalProperties: false } },
      }, required: ["key", "name", "columns", "lookup_columns", "rows"], additionalProperties: false },
    },
    symbolic_lines: { type: "array", items: { type: "object", properties: { key, role: { type: "string", minLength: 1, maxLength: 100 }, subcategory_key: key, plane: { enum: ["xy", "xz", "yz"] }, points_mm: { type: "array", minItems: 2, items: point3 }, visibility_parameter: key, visibility }, required: ["key", "role", "plane", "points_mm", "visibility"], additionalProperties: false } },
    model_lines: { type: "array", items: { type: "object", properties: { key, role: { type: "string", minLength: 1, maxLength: 100 }, subcategory_key: key, plane: { enum: ["xy", "xz", "yz"] }, points_mm: { type: "array", minItems: 2, items: point3 }, endpoint_bindings: { type: "array", minItems: 1, items: modelLineEndpointBinding }, visibility_parameter: key, visibility }, required: ["key", "role", "plane", "points_mm", "visibility"], additionalProperties: false } },
    detail_level_representations: { type: "array", items: { type: "object", properties: { key, policy: { enum: familyDetailLevelRepresentationPolicies }, physical_part_keys: { type: "array", minItems: 1, uniqueItems: true, items: key }, symbolic_line_keys: { type: "array", minItems: 1, uniqueItems: true, items: key }, model_line_keys: { type: "array", minItems: 1, uniqueItems: true, items: key } }, required: ["key", "policy", "physical_part_keys"], additionalProperties: false } },
    controls: { type: "array", items: { type: "object", properties: { key, shape: { enum: ["vertical_arrow", "horizontal_arrow", "double_vertical_arrow", "double_horizontal_arrow"] }, view_plane: { enum: ["xy", "xz", "yz"] }, position_mm: point3 }, required: ["key", "shape", "view_plane", "position_mm"], additionalProperties: false } },
    detail_lines: { type: "array", items: { type: "object", properties: { key, role: { type: "string", minLength: 1, maxLength: 100 }, subcategory_key: key, plane: { enum: ["xy", "xz", "yz"] }, points_mm: { type: "array", minItems: 2, items: point3 }, endpoint_bindings: { type: "array", minItems: 1, items: modelLineEndpointBinding } }, required: ["key", "role", "plane", "points_mm"], additionalProperties: false } },
    filled_regions: { type: "array", items: { type: "object", properties: { key, role: { type: "string", minLength: 1, maxLength: 100 }, plane: { enum: ["xy", "xz", "yz"] }, type_name: { type: "string", minLength: 1, maxLength: 120 }, boundary_loops: { type: "array", minItems: 1, items: { type: "object", properties: { points_mm: { type: "array", minItems: 3, items: point3 } }, required: ["points_mm"], additionalProperties: false } } }, required: ["key", "role", "plane", "type_name", "boundary_loops"], additionalProperties: false } },
    profile_loops: { type: "array", items: { type: "object", properties: { key, role: { type: "string", minLength: 1, maxLength: 100 }, subcategory_key: key, plane: { enum: ["xy", "xz", "yz"] }, points_mm: { type: "array", minItems: 3, items: point3 } }, required: ["key", "role", "plane", "points_mm"], additionalProperties: false } },
    tag_background: { enum: ["transparent", "opaque"] }, tag_labels: { type: "array", minItems: 1, items: tagLabel },
    reference_plane_subcategories: { type: "array", items: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 120 }, color_rgb: rgb, projection_line_weight: { type: "integer", minimum: 1, maximum: 16 }, line_pattern_name: { type: "string", minLength: 1, maxLength: 120 } }, required: ["key", "name", "color_rgb", "projection_line_weight"], additionalProperties: false } },
    reference_planes: { type: "array", items: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 120 }, view_plane: { enum: ["xy", "xz", "yz"] }, bubble_end_mm: point3, free_end_mm: point3, cut_vector: point3, strength: { enum: ["not_reference", "weak", "strong"] }, reference_type: { enum: familyReferenceTypes }, defines_origin: { type: "boolean" }, subcategory_key: key }, required: ["key", "name", "view_plane", "bubble_end_mm", "free_end_mm", "cut_vector"], anyOf: [{ required: ["reference_type"] }, { required: ["strength"] }], additionalProperties: false } },
    reference_lines: { type: "array", items: { type: "object", properties: { key, plane: { enum: ["xy", "xz", "yz"] }, start_mm: point3, end_mm: point3 }, required: ["key", "plane", "start_mm", "end_mm"], additionalProperties: false } },
    dimensions: { type: "array", items: { type: "object", properties: { key, kind: { enum: ["linear", "radial", "angular"] }, view_plane: { enum: ["xy", "xz", "yz"] }, reference_keys: { type: "array", minItems: 2, uniqueItems: true, items: key }, line_start_mm: point3, line_end_mm: point3, parameter_key: key, equality: { type: "boolean" }, part_key: key, profile_loop_index: { type: "integer", minimum: 0, maximum: 1 }, leader_point_mm: point3, arc_center_mm: point3, arc_radius_mm: { type: "number", exclusiveMinimum: 0 }, start_angle_degrees: { type: "number" }, end_angle_degrees: { type: "number" } }, required: ["key", "view_plane"], additionalProperties: false } },
    alignments: { type: "array", items: { type: "object", properties: { key, view_plane: { enum: ["xy", "xz", "yz"] }, reference_plane_key: key, part_key: key, part_face: { enum: ["start", "end", "positive_y", "negative_y", "positive_z", "negative_z"] } }, required: ["key", "view_plane", "reference_plane_key", "part_key", "part_face"], additionalProperties: false } },
    arrays: { type: "array", items: { type: "object", properties: { key, member_part_keys: { type: "array", minItems: 1, uniqueItems: true, items: key }, member_nested_component_keys: { type: "array", minItems: 1, uniqueItems: true, items: key }, view_plane: { enum: ["xy", "xz", "yz"] }, count: { type: "integer", minimum: 2 }, count_parameter: key, direction_mm: point3, anchor: { enum: ["second", "last"] } }, required: ["key", "view_plane", "direction_mm", "anchor"], additionalProperties: false } },
    nested_components: { type: "array", items: { type: "object", properties: { key, blueprint_id: { type: "string", minLength: 1, maxLength: 100 }, created_from_blueprint: { enum: [true] }, type_name: { type: "string", minLength: 1, maxLength: 120 }, sharing: { enum: ["embedded", "shared"] }, shared_parameter_map_mode: { enum: ["identity_only"] }, family_type_parameter_key: key, type_options: { type: "array", minItems: 2, items: { type: "object", properties: { key, blueprint_id: { type: "string", minLength: 1, maxLength: 100 }, created_from_blueprint: { enum: [true] }, type_name: { type: "string", minLength: 1, maxLength: 120 }, sharing: { enum: ["embedded", "shared"] } }, required: ["key", "blueprint_id", "created_from_blueprint", "type_name"], additionalProperties: false } }, placement_mode: { enum: ["level_point", "host_face_point", "host_face_line"] }, host_part_key: key, host_face: { enum: ["start", "end", "positive_y", "negative_y", "positive_z", "negative_z"] }, placement_point_mm: point3, reference_direction: point3, placement_line_start_mm: point3, placement_line_end_mm: point3, rotation_axis: { enum: ["x", "y", "z"] }, rotation_degrees: { type: "number" }, parameter_map: { type: "object", additionalProperties: key }, visibility_parameter: key }, required: ["key", "parameter_map"], additionalProperties: false } },
    mirrors: { type: "array", items: { type: "object", properties: { key, target_kind: { enum: ["part", "nested_component"] }, target_keys: { type: "array", minItems: 1, uniqueItems: true, items: key }, plane_origin_mm: point3, plane_normal: point3, copy: { type: "boolean" } }, required: ["key", "target_kind", "target_keys", "plane_origin_mm", "plane_normal", "copy"], additionalProperties: false } },
    publication: { type: "object", properties: { compact_rfa: { type: "boolean" }, preview_view: { enum: ["auto", "three_dimensional", "none"] }, purge_unused: { type: "object", properties: { scope: { enum: ["template_residue"] }, max_passes: { type: "integer", minimum: 1, maximum: 10 }, unsupported_behavior: { enum: ["fail", "skip_with_evidence"] } }, required: ["scope"], additionalProperties: false }, type_catalog: { type: "object", properties: { parameter_keys: { type: "array", minItems: 1, uniqueItems: true, items: key } }, required: ["parameter_keys"], additionalProperties: false } }, additionalProperties: false },
    verification: { type: "object", properties: { parameter_flex_cases: { type: "array", uniqueItems: true, items: { type: "object", properties: { parameter_key: key, min: { type: "number" }, nominal: { type: "number" }, max: { type: "number" } }, required: ["parameter_key", "min", "nominal", "max"], additionalProperties: false } } }, additionalProperties: false },
    ui_fallbacks: { type: "array", items: { type: "object", properties: { action: key, reason: { type: "string", minLength: 1, maxLength: 240 }, requires_human_checkpoint: { enum: [true] } }, required: ["action", "reason", "requires_human_checkpoint"], additionalProperties: false } },
  },
  required: ["schema_version", "target_lod", "family", "required_source_fields", "parameters", "types", "parts", "connectors"], additionalProperties: false,
} as const;

/** PDF/CAD evidence and adapter tools.  These schemas intentionally expose
 * only mapped fields; arbitrary Revit geometry/parameters are not accepted. */
export function registerFamilyPlatformTools(): Tool[] {
  return [
    defineTool("family_acceptance_matrix", "Trả ma trận nghiệm thu Family MEP và kiểm tính đầy đủ của evidence Revit 2023 → 2025. Tool không tự tạo evidence hoặc chứng nhận RFA/Project.", {
      type: "object", properties: { evidence: { type: "array", maxItems: 5000, items: acceptanceEvidence } }, additionalProperties: false,
    }),
    defineTool("revit_computer_use_assess", "Đánh giá evidence Computer Use trên whitelist Revit; chỉ đủ điều kiện review khi có 20 lần an toàn liên tiếp, ma trận runtime đầy đủ, cancel, dialog/security detection và read-back độc lập. Không điều khiển UI.", {
      type: "object", properties: { workflow: { enum: ["tag_label", "sweep_profile_label", "family_parameter_association", "visual_style_evidence"] }, runs: { type: "array", maxItems: 500, items: computerUseRun } }, required: ["workflow", "runs"], additionalProperties: false,
    }),
    defineTool("mepf_evidence_readiness", "Lập ma trận thông tin/bằng chứng bắt buộc và hỏi-gộp các điểm còn thiếu trước dựng Family, route hoặc Project MEPF. Chỉ ghi record cục bộ có checksum; không suy giá trị hoặc sửa Revit.", {
      type: "object", properties: { target_kind: { enum: ["family", "project", "route", "linework"] }, mapping: { enum: ["family_blueprint", "family_profile", "symbolic_lines", "model_lines", "detail_lines", "route_centerline", "image_family", "pdf_catalog_family", "mep_project_reconstruction"] }, evidence_ids: { type: "array", minItems: 1, maxItems: 20, uniqueItems: true, items: { type: "string", minLength: 1, maxLength: 96 } }, facts: { type: "object" } }, required: ["target_kind", "mapping", "evidence_ids"], additionalProperties: false,
    }),
    defineTool("cad_annotation_assess", "Đánh giá text/MTEXT/block attribute/dimension/LEADER CAD theo handle bất biến. Không ghép annotation với line theo khoảng cách; MLEADER/table/xref cần trusted adapter có provenance.", {
      type: "object", properties: { evidence_id: { type: "string", minLength: 1, maxLength: 96 }, required_metadata: { type: "array", maxItems: 20, uniqueItems: true, items: { enum: ["text", "mtext", "block_attribute", "dimension", "leader", "mleader", "table", "xref"] } }, associations: { type: "array", maxItems: 500, items: { type: "object", properties: { annotation_handle: { type: "string", minLength: 1, maxLength: 96 }, leader_handle: { type: "string", minLength: 1, maxLength: 96 }, target_entity_handle: { type: "string", minLength: 1, maxLength: 96 }, semantics: { type: "object" }, engineer_confirmed: { enum: [true] } }, required: ["annotation_handle", "target_entity_handle", "semantics", "engineer_confirmed"], additionalProperties: false } } }, required: ["evidence_id"], additionalProperties: false,
    }),
    defineTool("manufacturer_catalog_inspect", "Đọc CSV/TSV catalogue do kỹ sư cung cấp trong thư mục đã duyệt; kiểm checksum, revision, schema/key/unit/range/duplicate và trả draft lookup table có provenance. Không tải catalogue hoặc sửa Family cũ.", {
      type: "object", properties: { source_path: sourcePath, approved_catalog_directory: sourcePath, catalogue_name: { type: "string", minLength: 1, maxLength: 120 }, manufacturer: { type: "string", minLength: 1, maxLength: 120 }, revision: { type: "string", minLength: 1, maxLength: 80 }, lookup_key_columns: { type: "array", minItems: 1, maxItems: 20, uniqueItems: true, items: { type: "string", minLength: 1, maxLength: 120 } }, columns: { type: "array", minItems: 2, maxItems: 80, items: { type: "object", properties: { source_column: { type: "string", minLength: 1, maxLength: 120 }, data_type: { enum: ["length", "number", "integer", "angle", "text"] }, unit: { enum: ["mm", "cm", "m", "inch", "ft", "degree", "radian", "none"] }, minimum: { type: "number" }, maximum: { type: "number" } }, required: ["source_column", "data_type"], additionalProperties: false } }, approved_mapping: { type: "object" }, previous_catalog_record_id: { type: "string", minLength: 8, maxLength: 96 }, lookup_table: { type: "object", properties: { key, name: { type: "string", minLength: 1, maxLength: 80 }, lookup_key_columns: { type: "array", minItems: 1, items: { type: "string", minLength: 1, maxLength: 120 } }, column_keys: { type: "object", additionalProperties: key } }, required: ["key", "name", "lookup_key_columns", "column_keys"], additionalProperties: false } }, required: ["source_path", "approved_catalog_directory", "catalogue_name", "manufacturer", "revision", "lookup_key_columns", "columns"], additionalProperties: false,
    }),
    defineTool("family_compatibility_assess", "So sánh hợp đồng Family nguồn/đích có Revit read-back: category, placement, shared GUID/type/scope, connector, Part Type/routing và nested dependency. Tên Family không đủ; thiếu evidence thì block/ask.", {
      type: "object", properties: { source_family: { type: "object" }, target_family: { type: "object" } }, required: ["source_family", "target_family"], additionalProperties: false,
    }),
    defineTool("mepf_engineering_review", "Review độc lập, xác định của Project reconstruction plan: service/system/kind, size, Level/elevation, slope/invert và boundary Family/hosting. Không thay cho các phép tính MEP được chứng nhận.", {
      type: "object", properties: { reconstruction_plan: { type: "object" }, calculation_boundary_acknowledged: { type: "boolean" } }, required: ["reconstruction_plan"], additionalProperties: false,
    }),
    defineTool("source_conflict_assess", "Đối chiếu revision/hash/datum và các fact cùng khóa giữa nhiều nguồn bất biến; mọi xung đột cần engineer resolution rõ ràng trước Preview.", {
      type: "object", properties: { sources: { type: "array", minItems: 2, maxItems: 20, items: { type: "object", properties: { evidence_id: { type: "string", minLength: 1, maxLength: 96 }, sha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" }, revision: { type: "string", minLength: 1, maxLength: 120 }, common_datum_key: { type: "string", minLength: 1, maxLength: 120 }, facts: { type: "object" } }, required: ["evidence_id", "common_datum_key", "facts"], additionalProperties: false } }, resolutions: { type: "array", maxItems: 200, items: { type: "object", properties: { key: { type: "string", minLength: 1, maxLength: 120 }, chosen_evidence_id: { type: "string", minLength: 1, maxLength: 96 }, engineer_confirmed: { enum: [true] } }, required: ["key", "chosen_evidence_id", "engineer_confirmed"], additionalProperties: false } } }, required: ["sources"], additionalProperties: false,
    }),
    defineTool("family_source_inspect", "Đọc PDF bản vẽ/ảnh công trình/DWG/DXF cục bộ và tạo SourceEvidence v3 có hash, unit/scale/orientation/provenance; không dựng hoặc sửa model.", {
      type: "object", properties: { source_path: sourcePath, source_kind: { enum: ["pdf", "image", "dwg", "dxf"] }, approved_demo_directory: sourcePath, units: { enum: ["mm", "cm", "m", "inch", "ft", "unknown"] }, orientation: { enum: ["front", "side", "top", "orthographic", "perspective", "unknown"] }, scale_anchors: { type: "array", maxItems: 20, items: { type: "object", properties: { pixel_distance: { type: "number", exclusiveMinimum: 0 }, real_distance: { type: "number", exclusiveMinimum: 0 }, unit: { enum: ["mm", "cm", "m", "inch", "ft"] }, label: { type: "string", maxLength: 120 } }, required: ["pixel_distance", "real_distance", "unit"], additionalProperties: false } }, sheet_metadata: { type: "array", maxItems: 60, items: pdfSheetMetadata }, site_capture: siteCapture, trusted_adapter_manifest: trustedDwgManifest, page: { type: "integer", minimum: 1 }, layers: { type: "array", items: { type: "string" } } },
      required: ["source_path", "source_kind", "approved_demo_directory"], additionalProperties: false,
    }),
    defineTool("family_artifact_inspect", "Mở tạm một RFA staging để Revit đọc version/category/Part Type/connector/Type rồi đóng không lưu. Không load/place, không sửa Project hay thay Family gần giống.", {
      type: "object", properties: { family_path: sourcePath, approved_demo_directory: sourcePath, expected_revit_version: { enum: ["2023", "2025"] } },
      required: ["family_path", "approved_demo_directory"], additionalProperties: false,
    }),
    defineTool("source_to_revit_proposal", "Map SourceEvidence v3 thành proposal MEPF: PDF/DWG/DXF/ảnh công trình → ProjectReconstructionPlan; hoặc PDF catalog/DXF/ảnh nhiều góc → Family/route bounded. Không sửa Revit.", {
      type: "object", properties: { evidence_ids: { type: "array", minItems: 1, maxItems: 20, uniqueItems: true, items: { type: "string", minLength: 1 } }, mapping: { enum: ["family_profile", "symbolic_lines", "model_lines", "detail_lines", "route_centerline", "image_family", "pdf_catalog_family", "mep_project_reconstruction"] }, readiness_record_id: { type: "string", minLength: 8, maxLength: 96 }, engineering_review_record_id: { type: "string", minLength: 8, maxLength: 96 }, source_conflict_record_id: { type: "string", minLength: 8, maxLength: 96 }, family_kind: key, type_name: { type: "string", minLength: 1, maxLength: 120 }, layers: { type: "array", uniqueItems: true, items: { type: "string", minLength: 1, maxLength: 120 } }, plane: { enum: ["xy", "xz", "yz"] }, confirm_units: { enum: ["mm", "cm", "m", "inch", "ft"] }, route: routeProposal, image_family: imageFamilyProposal, catalog_family: catalogFamilyProposal, mep_project: mepProjectProposal }, required: ["evidence_ids", "mapping"], additionalProperties: false,
    }),
    defineTool("family_spec_preview", "Chuẩn hóa SourceEvidence thành FamilySpec. Family Blueprint v3 cho phép mô tả Family MEP mới bằng primitive/parameter/connector có giới hạn, không nhận code tùy ý.", {
      type: "object", properties: { evidence_id: { type: "string", minLength: 1 }, supporting_evidence_ids: { type: "array", maxItems: 3, uniqueItems: true, items: { type: "string", minLength: 1 } }, readiness_record_id: { type: "string", minLength: 8, maxLength: 96, description: "Bắt buộc để spec có thể build-preview-ready: record mepf_evidence_readiness target_kind=family, khớp chính xác toàn bộ SourceEvidence và mapping Family. Nếu thiếu, tool trả câu hỏi-gộp và chặn Preview." }, family_kind: key, confirmed_fields: { type: "object", description: "Mỗi field có thể là scalar legacy (được ghi rõ là user_confirmed) hoặc { value, status?, provenance }. provenance chỉ nhận { kind: user_confirmed } hoặc { kind: source_document, page, block_index, block_sha256 } từ family_source_inspect; locator được kiểm với SourceEvidence bất biến." }, type_confirmed_fields: { type: "object", description: "Bắt buộc khi Blueprint có từ hai Family Type và required_source_fields: mapping exact Family Type name → confirmed_fields. Mỗi parameter source-bound phải có value tường minh bằng field đã xác nhận của chính Type đó; không dùng source fallback chung." }, catalog_revision: { ...catalogRevision, description: "Catalog identity tùy chọn cho Family một Type; revision_provenance phải là locator source_document hoặc user_confirmed rõ ràng, rồi được băm cùng SourceEvidence. Với Family có nhiều Type/source field, dùng type_catalog_revisions và khai rõ cho từng Type." }, type_catalog_revisions: { ...typeCatalogRevisions, description: "Mapping exact Family Type name → catalog identity. Mỗi revision phải có locator/xác nhận riêng; chỉ hợp lệ cho Family nhiều Type có required_source_fields, không bỏ sót hoặc dùng fallback revision chung." }, blueprint: familyBlueprintSchema, approved_demo_directory: sourcePath, notes: { type: "string" } },
      required: ["evidence_id", "family_kind"], additionalProperties: false,
    }),
    defineTool("family_build_preview", "Preview Family adapter HVAC trong tài liệu tạm rồi rollback; trả geometry, parameter, formula, connector và finding.", {
      type: "object", properties: { spec_id: { type: "string", minLength: 1 }, family_kind: key, template_path: { ...sourcePath, description: "Tùy chọn nâng cao; bỏ trống để MCP tự chọn template đúng Revit/category/hosting." }, approved_demo_directory: sourcePath, family_name: { type: "string", minLength: 1, maxLength: 80 }, type_name: { type: "string", minLength: 1, maxLength: 80 }, lod: { enum: ["LOD_300", "LOD_350"] }, connector_mode: { enum: ["none", "round_hvac"] } },
      required: ["spec_id", "family_kind", "approved_demo_directory", "family_name", "type_name", "lod"], additionalProperties: false,
    }, true),
    defineTool("family_build_apply", "Apply duy nhất preview Family đã xác nhận; staging GUID, reopen/checksum/read-back và không ghi đè output.", {
      type: "object", properties: { preview_id: { type: "string", minLength: 1 } }, required: ["preview_id"], additionalProperties: false,
    }, true),
    defineTool("cad_geometry_inspect", "Parse DXF whitelist hoặc xác thực manifest DWG bằng SHA-256. Với use_revit_trusted_adapter=true, Revit import DWG vào Family document tạm, đọc geometry/layer rồi rollback và đóng không lưu; không chạm Project, explode hoặc import mù.", {
      type: "object", properties: { source_path: sourcePath, approved_demo_directory: sourcePath, units: { enum: ["mm", "cm", "m", "inch", "ft", "unknown"] }, layers: { type: "array", items: { type: "string" } }, use_revit_trusted_adapter: { type: "boolean" }, trusted_adapter_manifest: trustedDwgManifest },
      required: ["source_path", "approved_demo_directory"], additionalProperties: false,
    }),
    defineTool("cad_to_revit_preview", "Map CAD evidence sang route/đối tượng Revit được adapter hỗ trợ và trả Change Set preview; geometry không map được thành finding.", {
      type: "object", properties: { evidence_id: { type: "string", minLength: 1 }, readiness_record_id: { type: "string", minLength: 8, maxLength: 96, description: "Bắt buộc cho mapping=route: mepf_evidence_readiness target_kind=route khớp CAD evidence. Thiếu record thì Change Set Preview bị chặn." }, context_id: { type: "string", minLength: 1 }, mapping: { enum: ["route", "reference_only"] }, kind: { enum: ["pipe", "duct", "conduit", "cable_tray"] }, type_id: { type: "integer", minimum: 1 }, system_type_id: { type: "integer", minimum: 1 }, level_id: { type: "integer", minimum: 1 }, elevation_mm: { type: "number" }, tolerance_mm: { type: "number", exclusiveMinimum: 0 }, layers: { type: "array", uniqueItems: true, items: { type: "string", minLength: 1, maxLength: 120 } }, confirm_units: { enum: ["mm", "cm", "m", "inch", "ft"] } },
      required: ["evidence_id", "context_id", "mapping", "confirm_units"], additionalProperties: false,
    }, true),
    defineTool("cad_to_revit_apply", "Apply atomic Change Set CAD đã xác nhận và trả post-commit verification/audit; không tự reroute.", {
      type: "object", properties: { preview_id: { type: "string", minLength: 1 } }, required: ["preview_id"], additionalProperties: false,
    }, true),
  ];
}
